// ignore_for_file: unnecessary_string_escapes, equal_keys_in_map

import 'package:get/get.dart';

final class LocalString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    //ENGLISH LANGUAGE
    'en_US': {
      //NEW
      "Good to see you again": "Good to see you again",
      "Welcome back to SIS. Let’s continue your journey!":
          "Welcome back to SIS. Let’s continue your journey!",
      "Enter Email Address": "Enter Email Address",
      "Enter Password": "Enter Password",
      "Forgot password?": "Forgot password?",
      "Sign In": "Sign In",
      "Continue with Google": "Continue with Google",
      "Don’t have an account?": "Don’t have an account?",
      "Register": "Register",
      "Please register to start your journey":
          "Please register to start your journey",
      "Welcome": "Welcome",
      "User Name": "User Name",
      "Email Address": "Email Address",
      "Password": "Password",
      "Confirm Password": "Confirm Password",
      "Confirm Password": "Confirm Password",
      "Already have an account?": "Already have an account?",
      "log In": "Log In",

      //Old
      "Delivery Man Info": "Delivery Man Info",
      "Do you want to exit the app?": "Do you want to exit the app?",
      "No": "No",
      "Yes": "Yes",
      "You need to log in first": "You need to log in first",
      "Profile": "Profile",
      "Pedidos": "Requests",
      "Pedidos   ": "Requests  ",
      "Search": "Search",
      "Home": "Home",
      "ERROR": "ERROR",
      "Confirm order": "Confirm order",
      "Adicionar morada": "Add adress",
      "Name of the address": "Nome do Endereço",
      "Rua do Outeiro": "Rua do Outeiro",
      "Address": "Morada",
      "Are you sure?": "Are you sure?",
      "Phone Number": "Phone Number",
      "City": "Cidade",
      "1º direito": "1º direito",
      "Enter to walk": "Enter to walk",
      "Postal Code": "Código Postal",
      "Enter Port Number": "Enter Port Number",
      "Country": "País",
      "Enter City": "Enter City",
      "State": "Estado",
      "Endereço padrão": "Default address",
      "Gravar": "Record",
      "Something went wrong": "Something went wrong",
      "Login successfully done": "Login successfully done",
      "Redefine password": "Redefine password",
      "Password": "Password",
      "Retype Password": "Retype Password",
      "Code": "Code",
      "Forgot your password": "Forgot your password",
      "Email": "Email",

      "Or login with": "Or login with",
      "Create Account": "Create Account",
      "First Name": "First Name",
      "First Name Can't be empty": "First Name Can't be empty",
      "Your Name": "Your Name",
      "Last Name": "Last Name",
      "Last Name Can't be empty": "Last Name Can't be empty",
      "Phone": "Phone",
      "phone number can't empty": "Phone number can't be empty",
      "Email Can't be empty": "Email Can't be empty",
      "Password must be  at least 6 characters":
          "Password must be  at least 6 characters",
      "Confim Password": "Confim Password",
      "Password Missmatch": "Password Missmatch",
      "Terms and Conditions": "Terms and Conditions",
      "I agree with terms and conditions and privacy policy":
          "I agree with terms and conditions and privacy policy",
      "Please accept the terms & condition!":
          "Please accept the terms & condition!",
      "Please check your internet connection":
          "Please check your internet connection",
      "Please login to perform this operation":
          "Please login to perform this operation",
      "Verify Otp": "Verify Otp",
      "verify provided otp": "verify provided otp",
      "Aplicar códido": "Aply code",
      "Aplicar": "Apply",
      "Enter Voucher": "Enter Voucher",
      "Voucher must be  at least 6 characters":
          "Voucher must be  at least 6 characters",
      "Adicionar código promocional": "Add promotional code",
      "Carrinho": "Cart",
      "O Teu Pedido": "Your request",
      " produto de ": "product",
      "Morada de entrega": "Delivery address",
      "Schedule delivery": "Schedule delivery",
      "Selecione um dia e hora": "Select a day and a hour",
      "Alterar": "Change",
      "Voucher Aplicado": "Aplyed voucher",
      "Tens um código promocional?": "You have a promotional code",
      "Sumário": "Summary",
      "Produtos": "Product",
      "Entrega": "Delivary",
      "Embalagem": "Package",
      "Total": "Total",
      "ar pedido": " request",
      "Select delivery Time": "Select delivery Time",
      "Agendar": "Schedule",
      "Cancelar": "Cancel",
      "Extras": "Extras",
      "Not Available": "Not Available",
      "Can't add more then 5 extra item": "Can't add more then 5 extra item",
      "Categories": "Categories",
      "Em destaque": "Highlighted",
      "Os seu favoritos": "Your favorits",
      "Opções": "Options",
      "Special Request": "Special Request",
      "Adicionar": "Add",
      "Add address To contiinue browsing": "Add address To contiinue browsing",
      "Entregar em": "Delivery in ",
      "Pesquisa": "Search",
      "Closed": "Closed",
      "VER TODOS": "SEE ALL",
      "Currently Not Available": "Currently Not Available",
      "Pedido": "Request",
      "Detalhes do pedido": "Request details",
      "Código de estafeta": "Code of the delivery boy",
      "Horário de entrega": "Delivery time",
      "Estado da encomenda": "Order state ",
      "Em curso": "On going",
      "Histórico": "History",
      "Pedir novamente": "Ask again",
      "Detalhes": "Details",
      "Seguir": "Follow",
      "Checkout": "Checkout",
      "Pagamenta": "Payment",
      "Add card": "Adicionar cartão",
      "Pagar": "Pay",
      "Select Payment Method": "Select Payment Method",
      "Perfil": "Profile",
      "As minhas moradas": "My adresses",
      "Ver os meus pedidos": "See my requests",
      "Contacto": "Contact",
      "Informações pessoais": "Personal information",
      "Preferências": "Preferences",
      "Idioma atual": "Current language",
      "Ajuda": "Help",
      "Enviar mensagem": "Send Message",
      "Conta": "Account",
      "You won't be able to revert this!": "You won't be able to revert this!",
      "Delete My Account": "Delete My Account",
      "You are about to Logout!": "You are about to Logout!",
      "Terminar sessão": "Log out",
      "Send Message": "Send Message",
      "Enter subject": "Enter subject",
      "Enter message": "Enter message",
      "message must be  at least 15 characters":
          "message must be  at least 15 characters",
      "No file selected": "No file selected",
      "Enter Value": "Enter Value",
      "Pesquisar": "Search",
      "Enter text": "Enter text",
      "Principais categorias": "Main categories",
      "Todas as categorias": "All categories",
      "Please select address from map": "Please select address from map",
      "Delivery Status": "Delivery Status",
      "Enter Address name": "Enter Address name",
      "Enter Address": "Enter Address",
      "Enter Postal Code": "Enter Postal Code",
      "Name on the card": "Name on the card",
      "Card Number": "Card Number",
      "Enter Card Name": "Enter Card Name",
      "Data de validade": "Expiration date",
      "Enter Expiry Date": "Enter Expiry Date",
      "Cartão padrão": "Standard card",
      "Cartão 1": "Card 1",
      "Old Password": "Old Password",
      "Enter oldPassword": "Enter oldPassword",
      "miss match old password": "miss match old password",
      "New Password": "New Password",
      "Enter newpassword": "Enter newpassword",
      "password must be 5 character": "password must be 5 character",
      " Password": " Password",
      "password not matched": "password not matched",
      "Andar": "To Walk",
      "Enter email": "Enter email",
      "email must be  at least 6 characters":
          "email must be  at least 6 characters",
      "NIF": "NIF",
      "Enter nif": "Enter nif",
      "nif must be  at least 6 characters":
          "nif must be  at least 6 characters",
      "Enter phone": "Enter phone",
      "phone must be  at least 6 characters":
          "phone must be  at least 6 characters",
      "Email": "Email",
      "Hoje": "Today",
      "Amanha": "Tomorrow",
      "Data connection is available.": "Data connection is available.",
      "You are not logged in": "You are not logged in",
      " minutes": " minutes",
      " unidades": " units",
      "Confirm Password": "Confirm Password",
      "Confirmed": "Confirmed",
      "Delivery Started": "Delivery Started",
      "Arrived at Shop": "Arrived at Shop",
      "Transit": "Transit",
      "Delivered": "Delivered",
      "On Transit": "On Transit",
      "ORDER FOR LATER": "ORDER FOR LATER",
      "OPEN NOW": "OPEN NOW",
      "This shop is closed now!": "This shop is closed now!",
      "Items": "Items",
      "Success": "Success",
      "Success with no content": "Success with no content",
      "Bad request. Try again later": "Bad request. Try again later",
      "User unauthorized. Try again later":
          "User unauthorized. Try again later",
      "Forbidden request. Try again later":
          "Forbidden request. Try again later",
      "Something went wrong. Try again later":
          "Something went wrong. Try again later",
      "URL not found. Try again later": "URL not found. Try again later",
      "Timeout. Try again later": "Timeout. Try again later",
      "Request canceled": "Request canceled",
      "Timeout. Try again later": "Timeout. Try again later",
      "Cache error. Try again later": "Cache error. Try again later",
      "Please check your internet connection":
          "Please check your internet connection",
      "Something went wrong": "Something went wrong",
      "Welcome to Wasel Canada": "Welcome to Wasel Canada",
      "Buy, Sell, Find Jobs, Discover Businesses, and Connect with Services across Canada.":
          "Buy, Sell, Find Jobs, Discover Businesses, and Connect with Services across Canada.",
      "Buy & Sell near you": "Buy & Sell near you",
      "Find your next job": "Find your next job",
      "Discover local businesses": "Discover local businesses",
      "Connect with services": "Connect with services",
      "Continue with Apple": "Continue with Apple",
      "Continue as Guest": "Continue as Guest",
      "OR": "OR",
      "Already have an account? ": "Already have an account? ",
      "Welcome Back": "Welcome Back",
      "Sign in to your Wasel Canada account":
          "Sign in to your Wasel Canada account",
      "Email address": "Email address",
      "your@email.com": "your@email.com",
      "Please enter your email address": "Please enter your email address",
      "Please enter a valid email address":
          "Please enter a valid email address",
      "Password": "Password",
      "Enter your password": "Enter your password",
      "Please enter your password": "Please enter your password",
      "Password must be at least 6 characters":
          "Password must be at least 6 characters",
      "Remember me": "Remember me",
      "Forget password?": "Forget password?",
      "Login": "Login",
      "Don't have an account? ": "Don't have an account? ",
      "Sign UP": "Sign UP",
      "Sign Up with Email": "Sign Up with Email",
      "Full Name": "Full Name",
      "Enter full name": "Enter full name",
      "Please enter your full name": "Please enter your full name",
      "Min. 6 characters": "Min. 6 characters",
      "Please enter a password": "Please enter a password",
      "Confirm Password": "Confirm Password",
      "Repeat password": "Repeat password",
      "Please repeat your password": "Please repeat your password",
      "Passwords do not match": "Passwords do not match",
      "Join the community and start exploring local opportunities.":
          "Join the community and start exploring local opportunities.",
      "Settings and Support": "Settings and Support",
      "My Content": "My Content",
      "My Listings": "My Listings",
      "Favorites": "Favorites",
      "Account": "Account",
      "Edit Profile": "Edit Profile",
      "Change Password": "Change Password",
      "Language": "Language",
      "Block User": "Block User",
      "Notification Settings": "Notification Settings",
      "Delete Account": "Delete Account",
      "Support": "Support",
      "Contact Us": "Contact Us",
      "About Wasel Canada": "About Wasel Canada",
      "Privacy Policy": "Privacy Policy",
      "Terms of Service": "Terms of Service",
      "Log Out": "Log Out",
      "Are you sure you want to log out of Wasel Canada?":
          "Are you sure you want to log out of Wasel Canada?",
      "Sign In/Create Account Now": "Sign In/Create Account Now",
      "Please sign in or create an account to access your profile, manage activities, and enjoy the full Wasel Canada experience.":
          "Please sign in or create an account to access your profile, manage activities, and enjoy the full Wasel Canada experience.",
      "Enter email address": "Enter email address",
      "Forgot Password": "Forgot Password",
      "Enter your email to reset your password and get back to making change": "Enter your email to reset your password and get back to making change",
      "OTP Verification": "OTP Verification",
      "To ensure the safety and reliability of our community, please enter the 4-digit OTP sent to ": "To ensure the safety and reliability of our community, please enter the 4-digit OTP sent to ",
      "Please enter the complete 4-digit OTP code": "Please enter the complete 4-digit OTP code",
      "Verify": "Verify",
      "Didn't receive code? ": "Didn't receive code? ",
      "Resend": "Resend",
      "Password Updated!": "Password Updated!",
      "Your password has been changed.\nYou’re all set to log in now.": "Your password has been changed.\nYou’re all set to log in now.",
      "Login Now": "Login Now",
      "New Password": "New Password",
      "Create a new password to continue your journey with Wasel Canada": "Create a new password to continue your journey with Wasel Canada",
      "Enter your new password": "Enter your new password",
      "Please enter your new password": "Please enter your new password",
      "Password must be at least 6 characters": "Password must be at least 6 characters",
      "Enter your confirm password": "Enter your confirm password",
      "Please repeat your new password": "Please repeat your new password",
      "The password field confirmation does not match.": "The password field confirmation does not match.",
      "Verify Your Email": "Verify Your Email",
      "Verify Email": "Verify Email",
      "Failed to load locations": "Failed to load locations",
      "Failed to load cities": "Failed to load cities",
      "Please select both province and city": "Please select both province and city",
      "Guest token is invalid or missing": "Guest token is invalid or missing",
      "Select Your Location": "Select Your Location",
      "Choose your province and city to personalize listings and recommendations.": "Choose your province and city to personalize listings and recommendations.",
      "Province/Territory": "Province/Territory",
      "Select province": "Select province",
      "City": "City",
      "Select province first": "Select province first",
      "Select city": "Select city",
      "Your location has been selected": "Your location has been selected",
      "You can change your location anytime from Settings": "You can change your location anytime from Settings",
      "Continue": "Continue",
      "What are you looking for?": "What are you looking for?",
      "See All": "See All",
      "See Less": "See Less",
      "Featured Listings": "Featured Listings",
      "Recent Listings": "Recent Listings",
      "Search Products": "Search Products",
      "Search products...": "Search products...",
      "Clear All": "Clear All",
      "Apply Filters": "Apply Filters",
      "Filtering...": "Filtering...",
      "Category": "Category",
      "Province": "Province",
      "Price Range": "Price Range",
      "Sort By": "Sort By",
      "Filters": "Filters",
      "About Business": "About Business",
      "Send Message": "Send Message",
      "Message": "Message",
      "Report User": "Report User",
      "Block User": "Block User",
      "Block": "Block",
      "Are you sure you want to block": "Are you sure you want to block",
      "You will no longer receive messages or see listings from this user.": "You will no longer receive messages or see listings from this user.",
      "Report this user": "Report this user",
      "Report this listing": "Report this listing",
      "Please select the reason for reporting user": "Please select the reason for reporting user",
      "Please select the reason for reporting listing": "Please select the reason for reporting listing",
      "Tell us more": "Tell us more",
      "Enter details here...": "Enter details here...",
      "Submit Report": "Submit Report",
      "No messages yet": "No messages yet",
      "Type message here...": "Type message here...",
      "of": "of",
      "1": "1",
      "2": "2",
      "3": "3",
      "4": "4",
      "5": "5",
      "6": "6",
      "Buy & Sell": "Buy & Sell",
      "Jobs": "Jobs",
      "Services": "Services",
      "Business Directory": "Business Directory",
      "Photos": "Photos",
      "Add up to 5 photos on your product. The first photo will be the main thumbnail.": "Add up to 5 photos on your product. The first photo will be the main thumbnail.",
      "Add Photo": "Add Photo",
      "Main": "Main",
      "photos added": "photos added",
      "Please add at least one photo.": "Please add at least one photo.",
      "Details": "Details",
      "Title": "Title",
      "Enter listing title": "Enter listing title",
      "Please enter a listing title": "Please enter a listing title",
      "Describe your item in detail...": "Describe your item in detail...",
      "Please describe your item": "Please describe your item",
      "Price": "Price",
      'e.g. \$500': 'e.g. \$500',
      "Please enter a price": "Please enter a price",
      "Please enter a valid numeric price": "Please enter a valid numeric price",
      "Condition": "Condition",
      "New": "New",
      "Like New": "Like New",
      "Good": "Good",
      "Fair": "Fair",
      "For Parts": "For Parts",
      "Please select a province": "Please select a province",
      "Please select a city": "Please select a city",
      "Address (Optional)": "Address (Optional)",
      "Street address or neighbourhood": "Street address or neighbourhood",
      "Select City": "Select City",
      "Search city...": "Search city...",
      "Choose how buyers can reach you. Enable at least one contact method.": "Choose how buyers can reach you. Enable at least one contact method.",
      "What's App Number": "What's App Number",
      "Enable in-App Chat": "Enable in-App Chat",
      "Allow buyers to message you in the app": "Allow buyers to message you in the app",
      "Submitting...": "Submitting...",
      "Please provide or enable at least one contact method.": "Please provide or enable at least one contact method.",
      "Review & Submit": "Review & Submit",
      "Review your listing details before submitting for approval.": "Review your listing details before submitting for approval.",
      "Before You Submit": "Before You Submit",
      "Your listing will be reviewed by our team": "Your listing will be reviewed by our team",
      "Review usually takes up to 24 hours": "Review usually takes up to 24 hours",
      "You'll be notified once approved": "You'll be notified once approved",
      "Approved listings become visible to all users": "Approved listings become visible to all users",
      "You can edit or remove your listing later": "You can edit or remove your listing later",
      "Submit Listing": "Submit Listing",
      "Explore": "Explore",
      "Exit App?": "Exit App?",
      "Are you sure you want to exit the app?": "Are you sure you want to exit the app?",
      "Exit": "Exit",
      "My Content": "My Content",
      "Account": "Account",
      "Support": "Support",
      "Language": "Language",
      "Delete Account": "Delete Account",
      "Delete Account Permanently?": "Delete Account Permanently?",
      "Are you sure you want to permanently delete your account? This action cannot be undone. Your profile, listings, messages, favorites, and account data will be permanently removed.": "Are you sure you want to permanently delete your account? This action cannot be undone. Your profile, listings, messages, favorites, and account data will be permanently removed.",
      "Continue Delete": "Continue Delete",
      "Confirm Your Password": "Confirm Your Password",
      "For security reasons, please enter your password to continue.": "For security reasons, please enter your password to continue.",
      "Password is required": "Password is required",
      "Your account will be permanently deleted after successful verification.": "Your account will be permanently deleted after successful verification.",
      "Delete Permanently": "Delete Permanently",
      "Back": "Back",
      "Sign In/Create Account Now": "Sign In/Create Account Now",
      "Please sign in or create an account to access your profile, manage activities, and enjoy the full Wasel Canada experience.": "Please sign in or create an account to access your profile, manage activities, and enjoy the full Wasel Canada experience.",
      "Sign In": "Sign In",
      "Create Account": "Create Account",
      "Settings and Support": "Settings and Support",
      "Keep your profile up to date by modifying your information.": "Keep your profile up to date by modifying your information.",
      "Full Name": "Full Name",
      "Enter your full name": "Enter your full name",
      "Please enter your name": "Please enter your name",
      "The current password field is required.": "The current password field is required.",
      "The new password field is required.": "The new password field is required.",
      "Password must be at least 6 characters long": "Password must be at least 6 characters long",
      "The confirm password field is required.": "The confirm password field is required.",
      "The confirm password field must match new password.": "The confirm password field must match new password.",
      "Control which updates and activities you want to receive": "Control which updates and activities you want to receive",
      "Notification Types": "Notification Types",
      "Enable Notifications": "Enable Notifications",
      "enabled": "enabled",
      "0": "0",
      "7": "7",
      "8": "8",
      "9": "9",
      "New Messages": "New Messages",
      "When someone sends you a message": "When someone sends you a message",
      "Marketing": "Marketing",
      "Promotions and tips from Wasel Canada": "Promotions and tips from Wasel Canada",
      "Email Notification": "Email Notification",
      "Receive updates via email": "Receive updates via email",
      "Changes to your notification preferences are saved automatically.": "Changes to your notification preferences are saved automatically.",
      "All": "All",
      "Pending": "Pending",
      "Active": "Active",
      "Expired": "Expired",
      "No listings found in": "No listings found in",
      "Pull down to refresh": "Pull down to refresh",
      "Delete Listing?": "Delete Listing?",
      "Are you sure you want to delete this listing? This action cannot be undone.": "Are you sure you want to delete this listing? This action cannot be undone.",
      "Listing Item": "Listing Item",
      "Listing deleted successfully": "Listing deleted successfully",
      "Awaiting admin review - not yet visible to others": "Awaiting admin review - not yet visible to others",
      "General": "General",
      "Canada": "Canada",
      "Featured": "Featured",
      "No Title": "No Title",
      "No favorites added yet": "No favorites added yet",
      "No favorites in": "No favorites in",
      "Blocked Users": "Blocked Users",
      "Manage blocked profiles, privacy restrictions, and connection safety settings.": "Manage blocked profiles, privacy restrictions, and connection safety settings.",
      "User": "User",
      "Blocked recently": "Blocked recently",
      "No Blocked Users": "No Blocked Users",
      "Profiles you block will appear here.": "Profiles you block will appear here.",
      "Language changed to": "Language changed to",
      "successfully!": "successfully!",
      "Failed to load about page information.": "Failed to load about page information.",
      "No data available.": "No data available.",
      "Contact Support": "Contact Support",
      "Describe your issue clearly so our support team can assist you faster.": "Describe your issue clearly so our support team can assist you faster.",
      "Support Request Form": "Support Request Form",
      "Tip: Include as much detail as possible about your issue. Screenshots, error messages, and step-by-step descriptions help our team resolve your issue faster.": "Tip: Include as much detail as possible about your issue. Screenshots, error messages, and step-by-step descriptions help our team resolve your issue faster.",
      "Send Support Request": "Send Support Request",
      "Email Support Response": "Email Support Response",
      "Our support team typically responds within 24-48 hours. You'll receive a response at your registered email address.": "Our support team typically responds within 24-48 hours. You'll receive a response at your registered email address.",
      "Please describe your issue or question in detail. Include any relevant information that will help our support team assist you better...": "Please describe your issue or question in detail. Include any relevant information that will help our support team assist you better...",
      "Click to upload screenshot": "Click to upload screenshot",
      "PNG, JPG up to 10MB": "PNG, JPG up to 10MB",
      "Your Email Address": "Your Email Address",
      "Please enter your email": "Please enter your email",
      "Please enter a valid email": "Please enter a valid email",
      "We'll send the response to this email address": "We'll send the response to this email address",
      "Subject (Optional)": "Subject (Optional)",
      "Enter your subject...": "Enter your subject...",
      "Describe Your Issue": "Describe Your Issue",
      "Please describe your issue": "Please describe your issue",
      "Attach Screenshot (Optional)": "Attach Screenshot (Optional)",
      "Messages": "Messages",
      "Search conversations...": "Search conversations...",
      "No conversations found": "No conversations found",
      "No messages yet": "No messages yet",
      "Select city": "Select city",
      "Select province first": "Select province first",
      "Min \$": "Min \$",
      "Max \$": "Max \$",
      "Newest First": "Newest First",
      "Oldest First": "Oldest First",
      "Price: Low to High": "Price: Low to High",
      "Price: High to Low": "Price: High to Low",
      "Business": "Business",
      "No listings found": "No listings found",
      "Try a different search or category": "Try a different search or category",
      "1 listing found": "1 listing found",
      "listings found": "listings found",
      "Protect your account by updating your password. Enter your current password and set a new one to keep your account safe.": "Protect your account by updating your password. Enter your current password and set a new one to keep your account safe.",
      "Current Password": "Current Password",
      "Enter your current password": "Enter your current password",
      "Create Listing": "Create Listing",
      "Choose the type of listing you would like to create.": "Choose the type of listing you would like to create.",
      "Description": "Description",
      "Location": "Location",
      "Contact": "Contact",
      "Listing Submitted\nSuccessfully": "Listing Submitted\nSuccessfully",
      "Your listing has been submitted and is currently awaiting admin approval. It will become visible to other users once approved.": "Your listing has been submitted and is currently awaiting admin approval. It will become visible to other users once approved.",
      "Review Time": "Review Time",
      "Usually within 24 hours": "Usually within 24 hours",
      "Notification": "Notification",
      "You'll be notified when approved or rejected": "You'll be notified when approved or rejected",
      "Visibility": "Visibility",
      "Hidden from public until approved": "Hidden from public until approved",
      "Status": "Status",
      "Back to Home": "Back to Home",
      "View My Listings": "View My Listings",
      "What's app number": "What's app number",
      "What's App Number": "What's App Number",
      "Downtown Toronto, Ontario": "Downtown Toronto, Ontario",
      "Like New / Excellent": "Like New / Excellent",
      "Toronto": "Toronto",
      "Manitoba": "Manitoba",
      "Job Photo Thumbnail": "Job Photo Thumbnail",
      "Add a photo to your job posting. This photo will be the main thumbnail.": "Add a photo to your job posting. This photo will be the main thumbnail.",
      "Upload Photo (PNG, JPG, or WEBP), maximum 5MB image.": "Upload Photo (PNG, JPG, or WEBP), maximum 5MB image.",
      "Job Info": "Job Info",
      "Job Title": "Job Title",
      "Enter job title": "Enter job title",
      "Please enter a job title": "Please enter a job title",
      "Company Name": "Company Name",
      "Enter company name": "Enter company name",
      "Please enter a company name": "Please enter a company name",
      "Job Description": "Job Description",
      "Describe the role, requirements, and responsibilities...": "Describe the role, requirements, and responsibilities...",
      "Please describe the job role": "Please describe the job role",
      "Job Type": "Job Type",
      "Full-Time": "Full-Time",
      "Part-Time": "Part-Time",
      "Contract": "Contract",
      "Remote": "Remote",
      "Temporary": "Temporary",
      "Enter Phone Number": "Enter Phone Number",
      "Enter WhatsApp Number": "Enter WhatsApp Number",
      "Your job opportunity has been submitted and is currently awaiting admin approval. It will become visible to other users once approved.": "Your job opportunity has been submitted and is currently awaiting admin approval. It will become visible to other users once approved.",
      "Status: Pending Approval": "Status: Pending Approval",
      "Images": "Images",
      "Upload a cover image and your business logo.": "Upload a cover image and your business logo.",
      "Cover Image": "Cover Image",
      "Upload Cover Image": "Upload Cover Image",
      "Recommended: 1200 × 400px": "Recommended: 1200 × 400px",
      "Business Logo": "Business Logo",
      "Add Logo": "Add Logo",
      "Square format recommended. Minimum 200 × 200px. PNG or JPG.": "Square format recommended. Minimum 200 × 200px. PNG or JPG.",
      "Please upload a cover image.": "Please upload a cover image.",
      "Please upload a business logo.": "Please upload a business logo.",
      "Business Info": "Business Info",
      "Business Name": "Business Name",
      "Enter business name": "Enter business name",
      "Please enter your business name": "Please enter your business name",
      "Business Category": "Business Category",
      "Enter business category": "Enter business category",
      "Website (Optional)": "Website (Optional)",
      "Business Hours": "Business Hours",
      "Sunday": "Sunday",
      "Monday": "Monday",
      "Tuesday": "Tuesday",
      "Wednesday": "Wednesday",
      "Thursday": "Thursday",
      "Friday": "Friday",
      "Saturday": "Saturday",
      "Tell customers about your business, services, and what makes you unique...": "Tell customers about your business, services, and what makes you unique...",
      "Please enter a description": "Please enter a description",
      "https://yourbusiness.ca": "https://yourbusiness.ca",
      "AM": "AM",
      "PM": "PM",
      "Business Gallery": "Business Gallery",
      "Showcase your business with additional photos. This step is optional.": "Showcase your business with additional photos. This step is optional.",
      "Upload Business Photos": "Upload Business Photos",
      "Add up to 10 photos (PNG, JPG, or WEBP), maximum 5MB per image.": "Add up to 10 photos (PNG, JPG, or WEBP), maximum 5MB per image.",
      "You can skip this step": "You can skip this step",
      "You can only add up to 10 photos.": "You can only add up to 10 photos.",
      "Contact Information": "Contact Information",
      "Configure how customers can contact your business. Add at least one contact channel.": "Configure how customers can contact your business. Add at least one contact channel.",
      "Enter phone number": "Enter phone number",
      "Enter whatsapp number": "Enter whatsapp number",
      "info@yourbusiness.ca": "info@yourbusiness.ca",
      "Enable In-App Chat": "Enable In-App Chat",
      "Allow users to send messages directly through the app.": "Allow users to send messages directly through the app.",
      "Please configure at least one active contact channel.": "Please configure at least one active contact channel.",
      "Please enter a valid email address": "Please enter a valid email address",
      "WhatsApp Number": "WhatsApp Number",
    },
    'ar': {
      "Categories": "الفئات",
      "Language Settings": "إعدادات اللغة",
      "Choose the language used throughout the application.":
          "اختر اللغة المستخدمة في التطبيق.",
      "Language changes will update the app interface instantly.":
          "ستعمل تغييرات اللغة على تحديث واجهة التطبيق على الفور.",
      "Welcome Back": "مرحبًا بعودتك",
      "Sign in to your Wasel Canada account":
          "تسجيل الدخول إلى حساب واصل كندا الخاص بك",
      "Email address": "عنوان البريد الإلكتروني",
      "your@email.com": "بريدك الإلكتروني",
      "Please enter your email address": "يرجى إدخال عنوان بريدك الإلكتروني",
      "Please enter a valid email address":
          "يرجى إدخال عنوان بريد إلكتروني صالح",
      "Password": "كلمة المرور",
      "Enter your password": "أدخل كلمة المرور الخاصة بك",
      "Please enter your password": "يرجى إدخال كلمة المرور",
      "Password must be at least 6 characters":
          "يجب أن تتكون كلمة المرور من ٦ أحرف على الأقل",
      "Remember me": "تذكرني",
      "Forget password?": "هل نسيت كلمة المرور؟",
      "Login": "تسجيل الدخول",
      "Don't have an account? ": "ليس لديك حساب؟ ",
      "Sign UP": "تسجيل الاشتراك",
      "Sign Up with Email": "تسجيل الاشتراك بالبريد الإلكتروني",
      "Save Changes": "حفظ التغييرات",
      "English": "الإنجليزية",
      "Arabic": "العربية",
      "Profile": "الملف الشخصي",
      "Home": "الرئيسية",
      "Search": "البحث",
      "Success": "نجاح",
      "Welcome": "مرحباً",
      "Sign In": "تسجيل الدخول",
      "Log In": "تسجيل الدخول",
      "Register": "تسجيل",
      "Confirm": "تأكيد",
      "Cancel": "إلغاء",
      "Good to see you again": "من الجيد رؤيتك مرة أخرى",
      "Welcome back to SIS. Let’s continue your journey!":
          "مرحبًا بك مجددًا في SIS. لنواصل رحلتك!",
      "Enter Email Address": "أدخل عنوان البريد الإلكتروني",
      "Enter Password": "أدخل كلمة المرور",
      "Forgot password?": "هل نسيت كلمة المرور؟",
      "Continue with Google": "المتابعة باستخدام جوجل",
      "Don’t have an account?": "ليس لديك حساب؟",
      "Please register to start your journey": "يرجى التسجيل لبدء رحلتك",
      "User Name": "اسم المستخدم",
      "Email Address": "عنوان البريد الإلكتروني",
      "Password": "كلمة المرور",
      "Confirm Password": "تأكيد كلمة المرور",
      "Already have an account?": "هل لديك حساب بالفعل؟",
      "Delivery Man Info": "معلومات عامل التوصيل",
      "Do you want to exit the app?": "هل تريد الخروج من التطبيق؟",
      "No": "لا",
      "Yes": "نعم",
      "You need to log in first": "يجب تسجيل الدخول أولاً",
      "Something went wrong": "حدث خطأ ما",
      "Please check your internet connection":
          "يرجى التحقق من اتصالك بالإنترنت",
      "Welcome to Wasel Canada": "مرحبًا بكم في واصل كندا",
      "Buy, Sell, Find Jobs, Discover Businesses, and Connect with Services across Canada.":
          "قم بالشراء والبيع والعثور على وظائف واكتشاف الشركات المحلية والتواصل مع الخدمات في جميع أنحاء كندا.",
      "Buy & Sell near you": "بيع وشراء بالقرب منك",
      "Find your next job": "ابحث عن وظيفتك التالية",
      "Discover local businesses": "اكتشف الشركات المحلية",
      "Connect with services": "اتصل بالخدمات",
      "Continue with Apple": "المتابعة باستخدام آبل",
      "Continue as Guest": "المتابعة كزائر",
      "OR": "أو",
      "Sign Up with Email": "تسجيل الاشتراك بالبريد الإلكتروني",
      "Already have an account? ": "هل لديك حساب بالفعل؟ ",
      "Full Name": "الاسم الكامل",
      "Enter full name": "أدخل الاسم الكامل",
      "Please enter your full name": "يرجى إدخال اسمك الكامل",
      "Min. 6 characters": "٦ أحرف كحد أدنى",
      "Please enter a password": "يرجى إدخال كلمة المرور",
      "Confirm Password": "تأكيد كلمة المرور",
      "Repeat password": "كرر كلمة المرور",
      "Please repeat your password": "يرجى تكرار كلمة المرور الخاصة بك",
      "Passwords do not match": "كلمات المرور غير متطابقة",
      "Join the community and start exploring local opportunities.":
          "انضم إلى المجتمع وابدأ في استكشاف الفرص المحلية.",
      "Settings and Support": "الإعدادات والدعم",
      "My Content": "محتواي",
      "My Listings": "إعلاناتي",
      "Favorites": "المفضلة",
      "Account": "الحساب",
      "Edit Profile": "تعديل الملف الشخصي",
      "Change Password": "تغيير كلمة المرور",
      "Language": "اللغة",
      "Block User": "المستخدمين المحظورين",
      "Notification Settings": "إعدادات الإشعارات",
      "Delete Account": "حذف الحساب",
      "Support": "الدعم",
      "Contact Us": "اتصل بنا",
      "About Wasel Canada": "حول واصل كندا",
      "Privacy Policy": "سياسة الخصوصية",
      "Terms of Service": "شروط الخدمة",
      "Log Out": "تسجيل الخروج",
      "Are you sure you want to log out of Wasel Canada?":
          "هل أنت متأكد أنك تريد تسجيل الخروج من واصل كندا؟",
      "Sign In/Create Account Now": "تسجيل الدخول / إنشاء حساب الآن",
      "Please sign in or create an account to access your profile, manage activities, and enjoy the full Wasel Canada experience.":
          "يرجى تسجيل الدخول أو إنشاء حساب للوصول إلى ملفك الشخصي وإدارة الأنشطة والاستمتاع بتجربة واصل كندا الكاملة.",
      "Create Account": "إنشاء حساب",
      "Enter email address": "أدخل عنوان البريد الإلكتروني",
      "Forgot Password": "نسيت كلمة المرور",
      "Enter your email to reset your password and get back to making change": "أدخل بريدك الإلكتروني لإعادة تعيين كلمة المرور والعودة لإحداث التغيير",
      "OTP Verification": "رمز التحقق",
      "To ensure the safety and reliability of our community, please enter the 4-digit OTP sent to ": "لضمان سلامة وموثوقية مجتمعنا، يرجى إدخال رمز التحقق المكون من ٤ أرقام المرسل إلى ",
      "Please enter the complete 4-digit OTP code": "يرجى إدخال رمز التحقق الكامل المكون من ٤ أرقام",
      "Verify": "التحقق",
      "Didn't receive code? ": "لم تتلقى الرمز؟ ",
      "Resend": "إعادة إرسال",
      "Password Updated!": "تم تحديث كلمة المرور!",
      "Your password has been changed.\nYou’re all set to log in now.": "تم تغيير كلمة المرور بنجاح.\nأنت جاهز تمامًا لتسجيل الدخول الآن.",
      "Login Now": "تسجيل الدخول الآن",
      "New Password": "كلمة مرور جديدة",
      "Create a new password to continue your journey with Wasel Canada": "قم بإنشاء كلمة مرور جديدة لمواصلة رحلتك مع واصل كندا",
      "Enter your new password": "أدخل كلمة المرور الجديدة",
      "Please enter your new password": "يرجى إدخال كلمة المرور الجديدة",
      "Password must be at least 6 characters": "يجب أن تكون كلمة المرور من ٦ أحرف على الأقل",
      "Enter your confirm password": "أدخل تأكيد كلمة المرور",
      "Please repeat your new password": "يرجى تكرار كلمة المرور الجديدة",
      "The password field confirmation does not match.": "تأكيد كلمة المرور غير متطابق.",
      "Verify Your Email": "التحقق من بريدك الإلكتروني",
      "Verify Email": "تحقق من البريد الإلكتروني",
      "Failed to load locations": "فشل في تحميل المواقع",
      "Failed to load cities": "فشل في تحميل المدن",
      "Please select both province and city": "يرجى تحديد المقاطعة والمدينة معًا",
      "Guest token is invalid or missing": "رمز الزائر غير صالح أو مفقود",
      "Select Your Location": "اختر موقعك",
      "Choose your province and city to personalize listings and recommendations.": "اختر المقاطعة والمدينة لتخصيص الإعلانات والتوصيات الموجهة لك.",
      "Province/Territory": "المقاطعة / الإقليم",
      "Select province": "اختر المقاطعة",
      "City": "المدينة",
      "Select province first": "اختر المقاطعة أولاً",
      "Select city": "اختر المدينة",
      "Your location has been selected": "تم تحديد موقعك",
      "You can change your location anytime from Settings": "يمكنك تغيير موقعك في أي وقت من الإعدادات",
      "Continue": "متابعة",
      "What are you looking for?": "عن ماذا تبحث؟",
      "See All": "عرض الكل",
      "See Less": "عرض أقل",
      "Featured Listings": "الإعلانات المميزة",
      "Recent Listings": "أحدث الإعلانات",
      "Search Products": "بحث المنتجات",
      "Search products...": "البحث عن منتجات...",
      "Clear All": "مسح الكل",
      "Apply Filters": "تطبيق الفلاتر",
      "Filtering...": "جاري التصفية...",
      "Category": "الفئة",
      "Province": "المقاطعة",
      "Price Range": "نطاق السعر",
      "Sort By": "ترتيب حسب",
      "Filters": "الفلاتر",
      "About Business": "حول العمل",
      "Send Message": "إرسال رسالة",
      "Message": "رسالة",
      "Report User": "الإبلاغ عن المستخدم",
      "Block User": "حظر المستخدم",
      "Block": "حظر",
      "Are you sure you want to block": "هل أنت متأكد أنك تريد حظر",
      "You will no longer receive messages or see listings from this user.": "لن تتلقى رسائل بعد الآن أو ترى الإعلانات من هذا المستخدم.",
      "Report this user": "الإبلاغ عن هذا المستخدم",
      "Report this listing": "الإبلاغ عن هذا الإعلان",
      "Please select the reason for reporting user": "يرجى تحديد سبب الإبلاغ عن المستخدم",
      "Please select the reason for reporting listing": "يرجى تحديد سبب الإبلاغ عن الإعلان",
      "Tell us more": "أخبرنا المزيد",
      "Enter details here...": "أدخل التفاصيل هنا...",
      "Submit Report": "تقديم البلاغ",
      "No messages yet": "لا توجد رسائل بعد",
      "Type message here...": "اكتب الرسالة هنا...",
      "of": "من",
      "1": "١",
      "2": "٢",
      "3": "٣",
      "4": "٤",
      "5": "٥",
      "6": "٦",
      "Buy & Sell": "شراء وبيع",
      "Jobs": "وظائف",
      "Services": "خدمات",
      "Business Directory": "دليل الأعمال",
      "Photos": "الصور",
      "Add up to 5 photos on your product. The first photo will be the main thumbnail.": "أضف ما يصل إلى ٥ صور لمنتجك. ستكون الصورة الأولى هي الصورة المصغرة الرئيسية.",
      "Add Photo": "إضافة صورة",
      "Main": "الرئيسية",
      "photos added": "صور مضافة",
      "Please add at least one photo.": "يرجى إضافة صورة واحدة على الأقل.",
      "Details": "تفاصيل",
      "Title": "العنوان",
      "Enter listing title": "أدخل عنوان الإعلان",
      "Please enter a listing title": "يرجى إدخال عنوان الإعلان",
      "Describe your item in detail...": "صف سلعتك بالتفصيل...",
      "Please describe your item": "يرجى وصف سلعتك",
      "Price": "السعر",
      'e.g. \$500': 'مثال: ٥٠٠\$',
      "Please enter a price": "يرجى إدخال السعر",
      "Please enter a valid numeric price": "يرجى إدخال سعر رقمي صالح",
      "Condition": "الحالة",
      "New": "جديد",
      "Like New": "شبه جديد",
      "Good": "جيد",
      "Fair": "مقبول",
      "For Parts": "قطع غيار",
      "Please select a province": "يرجى اختيار المقاطعة",
      "Please select a city": "يرجى اختيار المدينة",
      "Address (Optional)": "العنوان (اختياري)",
      "Street address or neighbourhood": "اسم الشارع أو الحي",
      "Select City": "اختر المدينة",
      "Search city...": "ابحث عن المدينة...",
      "Choose how buyers can reach you. Enable at least one contact method.": "اختر كيف يمكن للمشترين التواصل معك. قم بتمكين طريقة اتصال واحدة على الأقل.",
      "What's App Number": "رقم الواتساب",
      "Enable in-App Chat": "تمكين الدردشة داخل التطبيق",
      "Allow buyers to message you in the app": "السماح للمشترين بمراسلتك داخل التطبيق",
      "Submitting...": "جاري التقديم...",
      "Please provide or enable at least one contact method.": "يرجى تقديم أو تمكين طريقة اتصال واحدة على الأقل.",
      "Review & Submit": "المراجعة والتقديم",
      "Review your listing details before submitting for approval.": "راجع تفاصيل إعلانك قبل تقديمه للموافقة.",
      "Before You Submit": "قبل التقديم",
      "Your listing will be reviewed by our team": "سيتم مراجعة إعلانك من قبل فريقنا",
      "Review usually takes up to 24 hours": "تستغرق المراجعة عادةً ما يصل إلى ٢٤ ساعة",
      "You'll be notified once approved": "سيتم إخطارك بمجرد الموافقة",
      "Approved listings become visible to all users": "تصبح الإعلانات المعتمدة مرئية لجميع المستخدمين",
      "You can edit or remove your listing later": "يمكنك تعديل أو إزالة إعلانك لاحقًا",
      "Submit Listing": "تقديم الإعلان",
      "Explore": "استكشف",
      "Exit App?": "هل تريد الخروج من التطبيق؟",
      "Are you sure you want to exit the app?": "هل أنت متأكد أنك تريد الخروج من التطبيق؟",
      "Exit": "خروج",
      "My Content": "محتواي",
      "Account": "الحساب",
      "Support": "الدعم",
      "Language": "اللغة",
      "Delete Account": "حذف الحساب",
      "Delete Account Permanently?": "حذف الحساب نهائيًا؟",
      "Are you sure you want to permanently delete your account? This action cannot be undone. Your profile, listings, messages, favorites, and account data will be permanently removed.": "هل أنت متأكد من رغبتك في حذف حسابك نهائيًا؟ لا يمكن التراجع عن هذا الإجراء. سيتم إزالة ملفك الشخصي وإعلاناتك ورسائلك والمفضلة وبيانات حسابك بشكل دائم.",
      "Continue Delete": "متابعة الحذف",
      "Confirm Your Password": "تأكيد كلمة المرور",
      "For security reasons, please enter your password to continue.": "لأسباب أمنية، يرجى إدخال كلمة المرور للمتابعة.",
      "Password is required": "كلمة المرور مطلوبة",
      "Your account will be permanently deleted after successful verification.": "سيتم حذف حسابك نهائيًا بعد نجاح عملية التحقق.",
      "Delete Permanently": "حذف نهائيًا",
      "Back": "رجوع",
      "Sign In/Create Account Now": "تسجيل الدخول / إنشاء حساب الآن",
      "Please sign in or create an account to access your profile, manage activities, and enjoy the full Wasel Canada experience.": "يرجى تسجيل الدخول أو إنشاء حساب للوصول إلى ملفك الشخصي وإدارة الأنشطة والاستمتاع بتجربة واصل كندا الكاملة.",
      "Sign In": "تسجيل الدخول",
      "Create Account": "إنشاء حساب",
      "Settings and Support": "الإعدادات والدعم",
      "Keep your profile up to date by modifying your information.": "حافظ على تحديث ملفك الشخصي عن طريق تعديل معلوماتك.",
      "Full Name": "الاسم الكامل",
      "Enter your full name": "أدخل اسمك الكامل",
      "Please enter your name": "يرجى إدخال اسمك",
      "The current password field is required.": "حقل كلمة المرور الحالية مطلوب.",
      "The new password field is required.": "حقل كلمة المرور الجديدة مطلوب.",
      "Password must be at least 6 characters long": "يجب أن تكون كلمة المرور ٦ أحرف على الأقل",
      "The confirm password field is required.": "حقل تأكيد كلمة المرور مطلوب.",
      "The confirm password field must match new password.": "يجب أن يتطابق حقل تأكيد كلمة المرور مع كلمة المرور الجديدة.",
      "Control which updates and activities you want to receive": "التحكم في التحديثات والأنشطة التي ترغب في تلقيها",
      "Notification Types": "أنواع التنبيهات",
      "Enable Notifications": "تمكين التنبيهات",
      "enabled": "مفعّل",
      "0": "٠",
      "7": "٧",
      "8": "٨",
      "9": "٩",
      "New Messages": "رسائل جديدة",
      "When someone sends you a message": "عندما يرسل لك شخص ما رسالة",
      "Marketing": "التسويق",
      "Promotions and tips from Wasel Canada": "العروض النصائح من واصل كندا",
      "Email Notification": "إشعارات البريد الإلكتروني",
      "Receive updates via email": "تلقي التحديثات عبر البريد الإلكتروني",
      "Changes to your notification preferences are saved automatically.": "يتم حفظ التغييرات على تفضيلات الإشعارات تلقائيًا.",
      "All": "الكل",
      "Pending": "قيد الانتظار",
      "Active": "نشط",
      "Expired": "منتهي الصلاحية",
      "No listings found in": "لم يتم العثور على إعلانات في",
      "Pull down to refresh": "اسحب لأسفل للتحديث",
      "Delete Listing?": "حذف الإعلان؟",
      "Are you sure you want to delete this listing? This action cannot be undone.": "هل أنت متأكد أنك تريد حذف هذا الإعلان؟ لا يمكن التراجع عن هذا الإجراء.",
      "Listing Item": "عنصر الإعلان",
      "Listing deleted successfully": "تم حذف الإعلان بنجاح",
      "Awaiting admin review - not yet visible to others": "في انتظار مراجعة المسؤول - غير مرئي للآخرين بعد",
      "General": "عام",
      "Canada": "كندا",
      "Featured": "مميز",
      "No Title": "بدون عنوان",
      "No favorites added yet": "لم يتم إضافة أي مفضلات بعد",
      "No favorites in": "لا توجد مفضلات في",
      "Blocked Users": "المستخدمون المحظورون",
      "Manage blocked profiles, privacy restrictions, and connection safety settings.": "إدارة الملفات الشخصية المحظورة، وقيود الخصوصية، وإعدادات أمان الاتصال.",
      "User": "المستخدم",
      "Blocked recently": "تم الحظر مؤخرًا",
      "No Blocked Users": "لا يوجد مستخدمون محظورون",
      "Profiles you block will appear here.": "ستظهر الملفات الشخصية التي تحظرها هنا.",
      "Language changed to": "تم تغيير اللغة إلى",
      "successfully!": "بنجاح!",
      "Failed to load about page information.": "فشل تحميل معلومات صفحة حول التطبيق.",
      "No data available.": "لا توجد بيانات متاحة.",
      "Contact Support": "الاتصال بالدعم",
      "Describe your issue clearly so our support team can assist you faster.": "صف مشكلتك بوضوح حتى يتمكن فريق الدعم لدينا من مساعدتك بشكل أسرع.",
      "Support Request Form": "نموذج طلب الدعم",
      "Tip: Include as much detail as possible about your issue. Screenshots, error messages, and step-by-step descriptions help our team resolve your issue faster.": "نصيحة: قم بتضمين أكبر قدر ممكن من التفاصيل حول مشكلتك. تساعد لقطات الشاشة ورسائل الخطأ والوصف التفصيلي فريقنا في حل مشكلتك بشكل أسرع.",
      "Send Support Request": "إرسال طلب الدعم",
      "Email Support Response": "الرد على دعم البريد الإلكتروني",
      "Our support team typically responds within 24-48 hours. You'll receive a response at your registered email address.": "عادةً ما يستجيب فريق الدعم لدينا في غضون ٢٤-٤٨ ساعة. ستتلقى ردًا على عنوان بريدك الإلكتروني المسجل.",
      "Please describe your issue or question in detail. Include any relevant information that will help our support team assist you better...": "يرجى وصف مشكلتك أو سؤالك بالتفصيل. قم بتضمين أي معلومات ذات صلة ستساعد فريق الدعم لدينا في مساعدتك بشكل أفضل...",
      "Click to upload screenshot": "انقر لتحميل لقطة الشاشة",
      "PNG, JPG up to 10MB": "PNG, JPG حتى ١٠ ميجابايت",
      "Your Email Address": "عنوان بريدك الإلكتروني",
      "Please enter your email": "يرجى إدخال بريدك الإلكتروني",
      "Please enter a valid email": "يرجى إدخال بريد إلكتروني صالح",
      "We'll send the response to this email address": "سنرسل الرد إلى عنوان البريد الإلكتروني هذا",
      "Subject (Optional)": "الموضوع (اختياري)",
      "Enter your subject...": "أدخل الموضوع...",
      "Describe Your Issue": "صف مشكلتك",
      "Please describe your issue": "يرجى وصف مشكلتك",
      "Attach Screenshot (Optional)": "إرفاق لقطة شاشة (اختياري)",
      "Messages": "الرسائل",
      "Search conversations...": "البحث في المحادثات...",
      "No conversations found": "لم يتم العثور على محادثات",
      "No messages yet": "لا توجد رسائل بعد",
      "Select city": "اختر المدينة",
      "Select province first": "اختر المقاطعة أولاً",
      "Min \$": "الحد الأدنى \$",
      "Max \$": "الحد الأقصى \$",
      "Newest First": "الأحدث أولاً",
      "Oldest First": "الأقدم أولاً",
      "Price: Low to High": "السعر: من الأقل إلى الأعلى",
      "Price: High to Low": "السعر: من الأعلى إلى الأقل",
      "Business": "أعمال",
      "No listings found": "لم يتم العثور على إعلانات",
      "Try a different search or category": "جرب بحثًا أو فئة مختلفة",
      "1 listing found": "تم العثور على إعلان واحد",
      "listings found": "إعلانات تم العثور عليها",
      "Protect your account by updating your password. Enter your current password and set a new one to keep your account safe.": "احمِ حسابك عن طريق تحديث كلمة المرور الخاصة بك. أدخل كلمة مرورك الحالية وعيّن كلمة مرور جديدة للحفاظ على أمان حسابك.",
      "Current Password": "كلمة المرور الحالية",
      "Enter your current password": "أدخل كلمة المرور الحالية",
      "Create Listing": "إنشاء إعلان",
      "Choose the type of listing you would like to create.": "اختر نوع الإعلان الذي ترغب في إنشائه.",
      "Description": "الوصف",
      "Location": "الموقع",
      "Contact": "الاتصال",
      "Phone Number": "رقم الهاتف",
      "Listing Submitted\nSuccessfully": "تم تقديم الإعلان\nبنجاح",
      "Your listing has been submitted and is currently awaiting admin approval. It will become visible to other users once approved.": "تم تقديم إعلانك وهو قيد الانتظار لموافقة المسؤول. سيكون مرئيًا للمستخدمين الآخرين بمجرد الموافقة عليه.",
      "Review Time": "وقت المراجعة",
      "Usually within 24 hours": "عادةً خلال ٢٤ ساعة",
      "Notification": "الإشعار",
      "You'll be notified when approved or rejected": "سيتم إخطارك عند القبول أو الرفض",
      "Visibility": "الظهور",
      "Hidden from public until approved": "مخفي عن العامة حتى تتم الموافقة عليه",
      "Status": "الحالة",
      "Back to Home": "العودة إلى الرئيسية",
      "View My Listings": "عرض إعلاناتي",
      "What's app number": "رقم الواتساب",
      "What's App Number": "رقم الواتساب",
      "Downtown Toronto, Ontario": "وسط تورونتو، أونتاريو",
      "Like New / Excellent": "شبه جديد / ممتاز",
      "Toronto": "تورونتو",
      "Manitoba": "مانيتوبا",
      "Job Photo Thumbnail": "الصورة المصغرة للوظيفة",
      "Add a photo to your job posting. This photo will be the main thumbnail.": "أضف صورة إلى إعلان الوظيفة الخاص بك. ستكون هذه الصورة هي الصورة المصغرة الرئيسية.",
      "Upload Photo (PNG, JPG, or WEBP), maximum 5MB image.": "تحميل صورة (PNG أو JPG أو WEBP)، بحد أقصى ٥ ميجابايت للصور.",
      "Job Info": "معلومات الوظيفة",
      "Job Title": "مسمى الوظيفة",
      "Enter job title": "أدخل مسمى الوظيفة",
      "Please enter a job title": "يرجى إدخال مسمى الوظيفة",
      "Company Name": "اسم الشركة",
      "Enter company name": "أدخل اسم الشركة",
      "Please enter a company name": "يرجى إدخال اسم الشركة",
      "Job Description": "وصف الوظيفة",
      "Describe the role, requirements, and responsibilities...": "صف الدور والمتطلبات والمسؤوليات...",
      "Please describe the job role": "يرجى وصف دور الوظيفة",
      "Job Type": "نوع الوظيفة",
      "Full-Time": "دوام كامل",
      "Part-Time": "دوام جزئي",
      "Contract": "عقد",
      "Remote": "عن بعد",
      "Temporary": "مؤقت",
      "Enter Phone Number": "أدخل رقم الهاتف",
      "Enter WhatsApp Number": "أدخل رقم الواتساب",
      "Your job opportunity has been submitted and is currently awaiting admin approval. It will become visible to other users once approved.": "لقد تم تقديم فرصة العمل الخاصة بك وهي بانتظار موافقة المسؤول حالياً. ستكون مرئية للمستخدمين الآخرين بمجرد الموافقة عليها.",
      "Status: Pending Approval": "الحالة: قيد الانتظار لموافقة المسؤول",
      "Images": "الصور",
      "Upload a cover image and your business logo.": "قم بتحميل صورة غلاف وشعار عملك التجاري.",
      "Cover Image": "صورة الغلاف",
      "Upload Cover Image": "تحميل صورة الغلاف",
      "Recommended: 1200 × 400px": "موصى به: ١٢٠٠ × ٤٠٠ بكسل",
      "Business Logo": "شعار العمل التجاري",
      "Add Logo": "إضافة شعار",
      "Square format recommended. Minimum 200 × 200px. PNG or JPG.": "يوصى بتنسيق مربع. الحد الأدنى ٢٠٠ × ٢٠٠ بكسل. صيغة PNG أو JPG.",
      "Please upload a cover image.": "يرجى تحميل صورة الغلاف.",
      "Please upload a business logo.": "يرجى تحميل شعار العمل التجاري.",
      "Business Info": "معلومات العمل التجاري",
      "Business Name": "اسم العمل التجاري",
      "Enter business name": "أدخل اسم العمل التجاري",
      "Please enter your business name": "يرجى إدخال اسم العمل التجاري",
      "Business Category": "فئة العمل التجاري",
      "Enter business category": "أدخل فئة العمل التجاري",
      "Website (Optional)": "الموقع الإلكتروني (اختياري)",
      "Business Hours": "ساعات العمل",
      "Sunday": "الأحد",
      "Monday": "الاثنين",
      "Tuesday": "الثلاثاء",
      "Wednesday": "الأربعاء",
      "Thursday": "الخميس",
      "Friday": "الجمعة",
      "Saturday": "السبت",
      "Closed": "مغلق",
      "Tell customers about your business, services, and what makes you unique...": "أخبر العملاء عن عملك التجاري وخدماتك وما يجعلك مميزاً...",
      "Please enter a description": "يرجى إدخال وصف",
      "https://yourbusiness.ca": "رابط الموقع",
      "AM": "ص",
      "PM": "م",
      "Business Gallery": "معرض الأعمال",
      "Showcase your business with additional photos. This step is optional.": "اعرض عملك التجاري بصور إضافية. هذه الخطوة اختيارية.",
      "Upload Business Photos": "تحميل صور العمل التجاري",
      "Add up to 10 photos (PNG, JPG, or WEBP), maximum 5MB per image.": "أضف ما يصل إلى ١٠ صور (PNG أو JPG أو WEBP)، بحد أقصى ٥ ميجابايت لكل صورة.",
      "You can skip this step": "يمكنك تخطي هذه الخطوة",
      "You can only add up to 10 photos.": "يمكنك إضافة ما يصل إلى ١٠ صور فقط.",
      "Contact Information": "معلومات الاتصال",
      "Configure how customers can contact your business. Add at least one contact channel.": "تكوين كيفية تواصل العملاء مع عملك التجاري. أضف قناة اتصال واحدة على الأقل.",
      "Enter phone number": "أدخل رقم الهاتف",
      "Enter whatsapp number": "أدخل رقم الواتساب",
      "info@yourbusiness.ca": "البريد الإلكتروني",
      "Enable In-App Chat": "تفعيل المحادثة داخل التطبيق",
      "Allow users to send messages directly through the app.": "السماح للمستخدمين بإرسال الرسائل مباشرة من خلال التطبيق.",
      "Please configure at least one active contact channel.": "يرجى تكوين قناة اتصال نشطة واحدة على الأقل.",
      "Please enter a valid email address": "يرجى إدخال عنوان بريد إلكتروني صالح",
      "WhatsApp Number": "رقم الواتساب",
    },
  };
}
