const List<String> provinces = [
  'Alberta',
  'British Columbia',
  'Manitoba',
  'New Brunswick',
  'Newfoundland and Labrador',
  'Nova Scotia',
  'Ontario',
  'Prince Edward Island',
  'Quebec',
  'Saskatchewan',
  'Northwest Territories',
  'Nunavut',
  'Yukon',
];

const Map<String, List<String>> citiesMap = {
  'Alberta': [
    'Calgary',
    'Edmonton',
    'Red Deer',
    'Lethbridge',
    'Medicine Hat',
    'Wood Buffalo',
  ],
  'British Columbia': [
    'Vancouver',
    'Surrey',
    'Burnaby',
    'Richmond',
    'Victoria',
    'Kelowna',
    'Coquitlam',
  ],
  'Manitoba': [
    'Winnipeg',
    'Brandon',
    'Steinbach',
    'Thompson',
    'Portage la Prairie',
  ],
  'New Brunswick': [
    'Moncton',
    'Saint John',
    'Fredericton',
    'Dieppe',
    'Miramichi',
  ],
  'Newfoundland and Labrador': [
    'St. John\'s',
    'Mount Pearl',
    'Corner Brook',
    'Conception Bay South',
  ],
  'Nova Scotia': ['Halifax', 'Sydney', 'Truro', 'New Glasgow', 'Glace Bay'],
  'Ontario': [
    'Toronto',
    'Ottawa',
    'Mississauga',
    'Brampton',
    'Hamilton',
    'London',
    'Markham',
    'Vaughan',
    'Kitchener',
    'Windsor',
  ],
  'Prince Edward Island': [
    'Charlottetown',
    'Summerside',
    'Stratford',
    'Cornwall',
  ],
  'Quebec': [
    'Montreal',
    'Quebec City',
    'Laval',
    'Gatineau',
    'Longueuil',
    'Sherbrooke',
    'Saguenay',
    'Levis',
  ],
  'Saskatchewan': [
    'Saskatoon',
    'Regina',
    'Prince Albert',
    'Moose Jaw',
    'Swift Current',
  ],
  'Northwest Territories': [
    'Yellowknife',
    'Inuvik',
    'Hay River',
    'Fort Smith',
  ],
  'Nunavut': ['Iqaluit', 'Rankin Inlet', 'Arviat', 'Baker Lake'],
  'Yukon': ['Whitehorse', 'Dawson City', 'Watson Lake'],
};
